name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Stop existing service
        run: |
              kill $(lsof -t -i:8000) || echo "No process running on port 8000"

      - name: Start service
        run: |
          cd /root/actions-runner/_work/pythontest/pythontest  
          uvicorn test:app --host 78.47.238.241 --port 8000 &
